audio:
  sample_rate: 16000         # in Hz
  channels: 1                # 1 for mono, 2 for stereo (for now can only be 1)
  format: wav                # audio format
  normalize: true            # normalize waveform between [-1, 1]
  trim: false                # trim leading/trailing silence (TODO)

mel_spectrogram:
  fft_window_duration: 0.15  # sample_rate * 0.15 = 150ms
  hop_duration: 0.015        # sample_rate * 0.015 = 15ms
  n_mels: 160                # number of Mel bins
  f_min: 0                   # minimum frequency (Hz)
  f_max: 8000                # maximum frequency

arpabet:                    #phoneme to id
  AA: 0
  AE: 1
  AH: 2
  AO: 3
  AW: 4
  AY: 5
  B: 6
  CH: 7
  D: 8
  DH: 9
  EH: 10
  ER: 11
  EY: 12
  F: 13
  G: 14
  HH: 15
  IH: 16
  IY: 17
  JH: 18
  K: 19
  L: 20
  M: 21
  N: 22
  NG: 23
  OW: 24
  OY: 25
  P: 26
  R: 27
  S: 28
  SH: 29
  T: 30
  TH: 31
  UH: 32
  UW: 33
  V: 34
  W: 35
  Y: 36
  Z: 37
  ZH: 38



